<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTxXqkm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTxXqkm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTxXqkm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTxXqkm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTxXqkm\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTxXqkm',
    'container.build_id' => '9a4f482a',
    'container.build_time' => 1652780538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTxXqkm');
