<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZeQB8Qq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZeQB8Qq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZeQB8Qq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZeQB8Qq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZeQB8Qq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZeQB8Qq',
    'container.build_id' => '430295e5',
    'container.build_time' => 1652784529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZeQB8Qq');
