<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImLNepD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImLNepD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerImLNepD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerImLNepD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerImLNepD\App_KernelDevDebugContainer([
    'container.build_hash' => 'ImLNepD',
    'container.build_id' => 'd69702fe',
    'container.build_time' => 1652820733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImLNepD');
